// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuU002mcevNkj3_LgoSlWkZywR8B0axJc',
    appId: '1:836368545332:web:e8cd9d830ec23508d5fc61',
    messagingSenderId: '836368545332',
    projectId: 'codefusion-f6d69',
    authDomain: 'codefusion-f6d69.firebaseapp.com',
    storageBucket: 'codefusion-f6d69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAweinjOYxjtCtDNEF9dU_uZjL6kBMDvio',
    appId: '1:836368545332:android:c2b95c2274a504f3d5fc61',
    messagingSenderId: '836368545332',
    projectId: 'codefusion-f6d69',
    storageBucket: 'codefusion-f6d69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3fV7KAJIF1vfmwcK9rsygwYt3oFfYfDM',
    appId: '1:836368545332:ios:a933e105985fc322d5fc61',
    messagingSenderId: '836368545332',
    projectId: 'codefusion-f6d69',
    storageBucket: 'codefusion-f6d69.firebasestorage.app',
    androidClientId: '836368545332-d61a5fgipi1neq2osb2a28f53vvfist6.apps.googleusercontent.com',
    iosClientId: '836368545332-6dfd2g5hfbf2kpersadmj87lp75jm295.apps.googleusercontent.com',
    iosBundleId: 'com.example.codefusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3fV7KAJIF1vfmwcK9rsygwYt3oFfYfDM',
    appId: '1:836368545332:ios:a933e105985fc322d5fc61',
    messagingSenderId: '836368545332',
    projectId: 'codefusion-f6d69',
    storageBucket: 'codefusion-f6d69.firebasestorage.app',
    androidClientId: '836368545332-d61a5fgipi1neq2osb2a28f53vvfist6.apps.googleusercontent.com',
    iosClientId: '836368545332-6dfd2g5hfbf2kpersadmj87lp75jm295.apps.googleusercontent.com',
    iosBundleId: 'com.example.codefusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuU002mcevNkj3_LgoSlWkZywR8B0axJc',
    appId: '1:836368545332:web:2709c2b6ec364d50d5fc61',
    messagingSenderId: '836368545332',
    projectId: 'codefusion-f6d69',
    authDomain: 'codefusion-f6d69.firebaseapp.com',
    storageBucket: 'codefusion-f6d69.firebasestorage.app',
  );
}
